openapi: 3.0.0
info:
  title: API Finance Manager
  version: 1.0.0
  description: Documentação modular

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  $ref: {}